theme: minima
title: Arjane
author: Arjane Kerkhoven
description: Welcome to my website! Find out more about me (Arjane) and about my past and current projects. I have my roots in biology, with a sprinkle of IT skills on the side and my heart in marketing. Currently, I'm looking for a job in marketing and communication in Oulu, preferably one that includes a lot of culture!
